# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "build"

steps:
  Clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "jcantosz/cf-pipeline-factory"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github-jesse"
    stage: "clone"
  UpdatePipelines:
    title: "Create or Update pipelines"
    type: "pipeline-trigger-merge"
    working_directory: '${{Clone}}/pipelines'
    scale:
      pipeline-factory:
        arguments:
          SPEC: pipeline-factory.yaml
      gradle-pipeline:
        arguments:
          SPEC: gradle-pipeline.yaml
